apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-go-feb2224-2
  janus-idp.io/tekton: test-go-feb2224-2
  backstage.io/kubernetes-id: test-go-feb2224-2
  backstage.io/kubernetes-namespace: rhtap 
  app.kubernetes.io/part-of: test-go-feb2224-2
resources: 
- deployment.yaml
- route.yaml
- service.yaml
